export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  resetPassword: "/reset-password",
  notifications: "/notifications",
  student: {
    root: "/student",
    dashboard: "/student/dashboard",
    onboarding: "/student/onboarding",
    profile: "/student/profile",
    marks: "/student/marks",
    attendance: "/student/attendance",
    assignments: "/student/assignments",
    weakTopics: "/student/weak-topics",
    readiness: "/student/readiness",
    studyPlanner: "/student/study-planner",
  },
  teacher: {
    root: "/teacher",
    dashboard: "/teacher",
    onboarding: "/teacher/onboarding",
    profile: "/teacher/profile",
    attendance: "/teacher/attendance",
    classes: "/teacher/classes",
    assignments: "/teacher/assignments",
    analytics: "/teacher/analytics",
    assistant: "/teacher/assistant",
    uploadData: "/teacher/upload-data",
    students: "/teacher/students",
    studentDetail: (studentId: string) =>
      `/teacher/students/${studentId}` as const,
  },
  admin: {
    root: "/admin",
    dashboard: "/admin",
    teachers: "/admin/teachers",
    students: "/admin/students",
    studentDetail: (studentId: string) =>
      `/admin/students/${studentId}` as const,
    classes: "/admin/classes",
    reports: "/admin/reports",
    settings: "/admin/settings",
    attendance: "/admin/attendance",
  },
  parent: {
    root: "/parent",
    dashboard: "/parent/dashboard",
    selectChild: "/parent/select-child",
    marks: "/parent/marks",
    attendance: "/parent/attendance",
    weakTopics: "/parent/weak-topics",
    alerts: "/parent/alerts",
    profile: "/parent/profile",
  },
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
